repositories:
  bootstrap:
    type: bootstrap
    source_dir: ./bootstrap

  phar.phpunit.de:
    type: phar.io
    url: https://phar.phpunit.de/phive.xml

  phpunit-github:
    type: github
    repository: sebastianbergmann/phpunit
    tool_name: phpunit

  # php mess detector https://phpmd.org
  phpmd-github:
    type: github
    repository: phpmd/phpmd
    tool_name: phpmd
