repositories:
  bootstrap:
    type: bootstrap
    source_dir: ./bootstrap

  phar.phpunit.de:
    type: phar.io
    url: https://phar.phpunit.de/phive.xml

  phpcpd-github:
    type: github
    repository: sebastianbergmann/phpcpd
    tool_name: phpcpd

  phploc-github:
    type: github
    repository: sebastianbergmann/phploc
    tool_name: phploc

  # php mess detector https://phpmd.org
  phpmd-github:
    type: github
    repository: phpmd/phpmd
    tool_name: phpmd

  phpunit-github:
    type: github
    repository: sebastianbergmann/phpunit
    tool_name: phpunit

  psalm-github:
    type: github
    repository: vimeo/psalm
    tool_name: psalm

  composer-require-checker-github:
    type: github
    repository: maglnet/ComposerRequireChecker
    tool_name: composer-require-checker
